
language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: nicolas.vanhoren@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: nicolas-van/react-contexting
    branch: master
